# Generated by Django 4.2.6 on 2023-11-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMOdel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('fatehr_name', models.CharField(max_length=40)),
                ('address', models.TextField()),
            ],
        ),
    ]
