# Generated by Django 4.2.6 on 2023-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0004_friend_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.CharField(default='rahim', max_length=40),
        ),
    ]
