# Generated by Django 4.2.6 on 2023-11-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0006_person_alter_friend_options_alter_me_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='id',
        ),
        migrations.AlterField(
            model_name='passport',
            name='pass_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a1.person')),
            ],
        ),
    ]
