# Generated by Django 4.2.6 on 2023-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0007_remove_passport_id_alter_passport_pass_num_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.ImageField(upload_to='')),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subjenct', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=11)),
                ('stu', models.ManyToManyField(to='a1.students')),
            ],
        ),
    ]
