# Generated by Django 4.2.6 on 2023-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('first_date', models.DateField(auto_now_add=True)),
                ('last_eidt', models.DateField(auto_now=True)),
                ('catogory', models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('FAMILY', 'FAMILY'), ('ACADEMIC', 'ACADEMIC'), ('JOB', 'JOB'), ('OTHER', 'OTHER')], max_length=50)),
            ],
        ),
    ]
