# Generated by Django 4.2.6 on 2023-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_mytask_edit_count_mytask_finished_date_mytask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='finished_date',
            field=models.DateTimeField(),
        ),
    ]
