# Generated by Django 4.2.6 on 2023-11-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0004_alter_mytask_finished_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytask',
            name='finished_date',
        ),
    ]
