# Generated by Django 4.2.6 on 2023-11-15 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0006_remove_mytask_catogory_remove_mytask_edit_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='desceipsion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mytask',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='mytask',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('FAMILY', 'FAMILY'), ('ACADEMIC', 'ACADEMIC'), ('JOB', 'JOB'), ('OTHER', 'OTHER')], default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='mytask',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytask',
            name='finished_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='mytask',
            name='first_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytask',
            name='last_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mytask',
            name='status',
            field=models.CharField(default='INCOMPLETED', max_length=20),
        ),
    ]
