# Generated by Django 4.2.6 on 2023-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0007_rename_desceipsion_mytask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
