# Generated by Django 4.2.6 on 2023-11-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_modle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('catogory', models.CharField(choices=[('THRILLER', 'THRILLER'), ('HORROR', 'HORROR')], max_length=50)),
                ('first_pub', models.DateField(auto_now_add=True)),
                ('last_pub', models.DateField(auto_now=True)),
            ],
        ),
    ]
