# Generated by Django 4.2.6 on 2023-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_modle',
            name='catogory',
            field=models.CharField(choices=[('THRILLER', 'THRILLER'), ('HORROR', 'HORROR')], max_length=50),
        ),
    ]
