# Generated by Django 4.2.6 on 2023-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_store_model',
            name='last_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
